# Generated by Django 6.0.3 on 2026-04-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False, verbose_name='Head of Department')),
                ('role', models.CharField(choices=[('HEADMASTER', 'Headmaster'), ('DEPUTY_HEAD', 'Deputy Headmaster'), ('SENIOR_TEACHER', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('COACH', 'Sports Coach'), ('ADMIN', 'Administrator')], default='TEACHER', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
